version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/shipit-api-server
    #file_exists_behavior: OVERWRITE
hooks:
 BeforeInstall:
  - location: scripts/beforeinstallscript
    timeout:  300
    runas: ubuntu
 AfterInstall:
  - location: scripts/afterinstallscript
    timeout:  300
    runas: ubuntu
    #stop 
